config:
  connection:
    platform: tpp
    url: https://my.tpp.instance.company.com # URL to TPP instance
    trustBundle: /path/to/my/trustbundle.pem # TrustBundle for TPP connection
    credentials:
      accessToken: '{{ Env "TPP_ACCESS_TOKEN" }}'
      refreshToken: '{{ Env "TPP_REFRESH_TOKEN" }}'
      clientId: vcert-sdk
certificateTasks:
  - name: myCertificate # Task Identifier
    renewBefore: 31d
    setEnvVars: ["thumbprint", "serial"] #will set environment variables VCERT_TASKNAME_THUMBPRINT and VCERT_TASKNAME_SERIAL
    request:
      csr: service
      keyPassword: "newPassword!"
      subject:
        # Templating needs to go between single quotes to avoid issues when refreshing tokens and saving back
        commonName: '{{ Hostname | ToLower -}}.{{- Env "USERDNSDOMAIN" | ToLower }}'
        country: US
        locality: Salt Lake City
        state: Utah
        organization: Venafi Inc
        orgUnits:
          - engineering
          - marketing
      zone: "Open Source\\vcert"
    installations:
      - format: PEM
        file: "/path/to/my/certificate/cert.pem"
        chainFile: "/path/to/my/certificate/chain.cer"
        keyFile: "/path/to/my/certificate/key.pem"
        afterInstallAction: "echo Success!!!"
