config:
  connection:
    platform: TLSPC # alternatively, VAAS can be used
    credentials:
      tenantId: '{{ Env "TLSPC_TENANT_ID" }}' # TLSPC tenant ID as environment variable
      externalJWT: '{{ Env "TLSPC_EXTERNAL_JWT" }}' # JWT from Identity Provider as environment variable
      #externalJWT: 'file:/path/to/jwt' # JWT from Identity Provider as file
certificateTasks:
  - name: myCertificate # Task Identifier, no relevance in tool run
    renewBefore: 31d
    request:
      csr: service
      keyPassword: "newPassword!"
      subject:
        # Templating needs to go between single quotes to avoid issues when refreshing tokens and saving back
        commonName: '{{ Hostname | ToLower -}}.{{- Env "USERDNSDOMAIN" | ToLower }}'
        country: US
        locality: Salt Lake City
        state: Utah
        organization: Venafi Inc
        orgUnits:
          - engineering
          - marketing
      zone: "Open Source\\vcert"
    installations:
      - format: PEM
        file: "/path/to/my/certificate/cert.cer"
        chainFile: "/path/to/my/certificate/chain.cer"
        keyFile: "/path/to/my/certificate/key.pem"
        afterInstallAction: "echo Success!!!"
